name: 🐛 Bug Report For lume.land Website
description: Report an issue if something isn't working as expected 🤔.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting to report an issue you've found on the lume website.
        Please fill in the template below. If unsure about something, just do as best
        as you're able. If you are reporting a visual glitch, it will be much easier
        for us to fix it when you attach a screenshot as well.
  - type: input
    attributes:
      label: 'URL:'
      description: The URL of the page you are reporting an issue on.
      placeholder: https://lume.land
    validations:
      required: true
  - type: input
    attributes:
      label: 'Browser Name:'
      description: What kind of browser are you using?
      placeholder: Safari
    validations:
      required: true
  - type: input
    attributes:
      label: 'Browser Version:'
      description: What version of browser are you using?
      placeholder: '16.1'
    validations:
      required: true
  - type: input
    attributes:
      label: 'Operating System:'
      description: What operating system are you using
        (Write it in full, with version number)?
      placeholder: 'MacOS 13.0'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'How to reproduce the issue:'
      placeholder: |
        1. What I did.
        2. What I expected to happen.
        3. What I actually got.
        4. If possible, images or videos are welcome.
    validations:
      required: true
